In [ ]:
import pandas as pd

# Load the dataset
df = pd.read_csv('/content/wfp_food_prices_mwi (3).csv')

df

,date,region,district,market,latitude,longitude,category,commodity,unit,priceflag,pricetype,currency,price,usdprice
0,#date,#adm1+name,#adm2+name,#loc+market+name,#geo+lat,#geo+lon,#item+type,#item+name,#item+unit,#item+price+flag,#item+price+type,#currency,#value,#value+usd
1,10/15/1990,NaN,NaN,National Average,NaN,NaN,non-food,Fuel (diesel),L,actual,Retail,MWK,1.9,0.7162
2,10/15/1990,NaN,NaN,National Average,NaN,NaN,non-food,"Fuel (kerosene, paraffin)",L,actual,Retail,MWK,1.22,0.4599
3,8/15/1991,NaN,NaN,National Average,NaN,NaN,non-food,Fuel (diesel),L,actual,Retail,MWK,2,0.6893
4,8/15/1991,NaN,NaN,National Average,NaN,NaN,non-food,"Fuel (kerosene, paraffin)",L,actual,Retail,MWK,1.22,0.4204
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46800,2/15/2024,Southern Region,Zomba,Songani,-15.3172219,35.3931368,pulses and nuts,Pigeon peas,KG,aggregate,Retail,MWK,1927.27,1.1563
46801,2/15/2024,Southern Region,Zomba,Thondwe,-15.48834523,35.23530078,cereals and tubers,Maize (new harvest),KG,aggregate,Retail,MWK,868.18,0.5209
46802,2/15/2024,Southern Region,Zomba,Thondwe,-15.48834523,35.23530078,pulses and nuts,Beans,KG,aggregate,Retail,MWK,3000,1.7999
46803,2/15/2024,Southern Region,Zomba,Thondwe,-15.48834523,35.23530078,pulses and nuts,Cowpeas,KG,aggregate,Retail,MWK,1963.64,1.1781
46804,2/15/2024,Southern Region,Zomba,Thondwe,-15.48834523,35.23530078,pulses and nuts,Pigeon peas,KG,aggregate,Retail,MWK,2000,1.2

In [ ]:
# View the first few rows of the dataset
print(df.head())

# Get a summary of the dataset
print(df.info())

# Get descriptive statistics
print(df.describe())

         date      region    district            market  latitude longitude  \
0       #date  #adm1+name  #adm2+name  #loc+market+name  #geo+lat  #geo+lon
1  10/15/1990         NaN         NaN  National Average       NaN       NaN
2  10/15/1990         NaN         NaN  National Average       NaN       NaN
3   8/15/1991         NaN         NaN  National Average       NaN       NaN
4   8/15/1991         NaN         NaN  National Average       NaN       NaN

     category                  commodity        unit         priceflag  \
0  #item+type                 #item+name  #item+unit  #item+price+flag
1    non-food              Fuel (diesel)           L            actual
2    non-food  Fuel (kerosene, paraffin)           L            actual
3    non-food              Fuel (diesel)           L            actual
4    non-food  Fuel (kerosene, paraffin)           L            actual

          pricetype   currency   price    usdprice
0  #item+price+type  #currency  #value  #value+usd
1            Retail        MWK     1.9      0.7162
2            Retail        MWK    1.22      0.4599
3            Retail        MWK       2      0.6893
4            Retail        MWK    1.22      0.4204
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46805 entries, 0 to 46804
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       46805 non-null  object
 1   region     46316 non-null  object
 2   district   46316 non-null  object
 3   market     46805 non-null  object
 4   latitude   46316 non-null  object
 5   longitude  46316 non-null  object
 6   category   46805 non-null  object
 7   commodity  46805 non-null  object
 8   unit       46805 non-null  object
 9   priceflag  46805 non-null  object
 10  pricetype  46805 non-null  object
 11  currency   46805 non-null  object
 12  price      46805 non-null  object
 13  usdprice   46805 non-null  object
dtypes: object(14)
memory usage: 5.0+ MB
None
              date           region district market    latitude   longitude  \
count        46805            46316    46316  46805       46316       46316
unique         323                4       32    131         126         123
top     11/15/2020  Southern Region   Nsanje  Marka  -17.123443  35.2285444
freq          3099            22798     3559   1063        1063        1063

                  category commodity   unit  priceflag pricetype currency  \
count                46805     46805  46805      46805     46805    46805
unique                   8        56     15          4         2        3
top     cereals and tubers     Maize     KG  aggregate    Retail      MWK
freq                 22292     13183  33106      26192     46804    46087

        price usdprice
count   46805    46805
unique  17020    12277
top        50   0.0657
freq     2411      431

In [ ]:
# Check for missing values
print(df.isnull().sum())

date           0
region       489
district     489
market         0
latitude     489
longitude    489
category       0
commodity      0
unit           0
priceflag      0
pricetype      0
currency       0
price          0
usdprice       0
dtype: int64

In [ ]:
# Reset index to ensure we have a continuous numerical index
df.reset_index(drop=True, inplace=True)

# Remove the first row by index
df = df.drop(index=0)

In [ ]:
# Filter for entries with "Blantyre" and "maize"
filtered_df = df[(df['district'] == 'Blantyre') & df['commodity'].str.contains('Maize', case=False, na=False)]

# Display the filtered dataset
print(filtered_df.head())

           date           region  district market     latitude   longitude  \
398   7/15/2003  Southern Region  Blantyre  Lunzu  -15.6528104  35.0207804
423   8/15/2003  Southern Region  Blantyre  Lunzu  -15.6528104  35.0207804
444   9/15/2003  Southern Region  Blantyre  Lunzu  -15.6528104  35.0207804
463  10/15/2003  Southern Region  Blantyre  Lunzu  -15.6528104  35.0207804
484  11/15/2003  Southern Region  Blantyre  Lunzu  -15.6528104  35.0207804

               category commodity unit priceflag pricetype currency  price  \
398  cereals and tubers     Maize   KG    actual    Retail      MWK  10.85
423  cereals and tubers     Maize   KG    actual    Retail      MWK    8.5
444  cereals and tubers     Maize   KG    actual    Retail      MWK   9.33
463  cereals and tubers     Maize   KG    actual    Retail      MWK  17.36
484  cereals and tubers     Maize   KG    actual    Retail      MWK  16.67

    usdprice
398   0.1163
423   0.0831
444   0.0863
463   0.1604
484   0.1544

In [ ]:
# Save the cleaned dataset
filtered_df.to_csv('cleaned_dataset.csv', index=False)

In [ ]:
# # Rename columns to remove any leading or trailing whitespace
# df.columns = df.columns.str.strip()

# # Filter the dataset to include only rows where the district is "Blantyre"
# df_blantyre = df[df['district'].str.strip().str.lower() == 'blantyre']

# # Display the first few rows of the cleaned dataset
# df_blantyre.head()

,date,region,district,market,latitude,longitude,category,commodity,unit,priceflag,pricetype,currency,price,usdprice
398,7/15/2003,Southern Region,Blantyre,Lunzu,-15.6528104,35.0207804,cereals and tubers,Maize,KG,actual,Retail,MWK,10.85,0.1163
423,8/15/2003,Southern Region,Blantyre,Lunzu,-15.6528104,35.0207804,cereals and tubers,Maize,KG,actual,Retail,MWK,8.5,0.0831
444,9/15/2003,Southern Region,Blantyre,Lunzu,-15.6528104,35.0207804,cereals and tubers,Maize,KG,actual,Retail,MWK,9.33,0.0863
463,10/15/2003,Southern Region,Blantyre,Lunzu,-15.6528104,35.0207804,cereals and tubers,Maize,KG,actual,Retail,MWK,17.36,0.1604
484,11/15/2003,Southern Region,Blantyre,Lunzu,-15.6528104,35.0207804,cereals and tubers,Maize,KG,actual,Retail,MWK,16.67,0.1544